### ISSUE TITLE
老大，以后还会更新吗？期待

### ISSUE THREAD

**Issue by sunbin7288** [HoldOnBro/LocalizeCFW#3]
老大，以后还会更新吗？期待

**Comment by HoldOnBro** [comment]
目测是没了，解铃还须系铃人

**Comment by ZerOri** [comment]
实在搞不懂CFW开发者意图，不想加入中文仅仅是为了提高小白使用门槛？

**Comment by HoldOnBro** [comment]
> 实在搞不懂CFW开发者意图，不想加入中文仅仅是为了提高小白使用门槛？

之前有部分人提供的中文包是剔除了介绍界面的广告的，这点显然触碰到了开发者的利益。我的这个汉化包只对界面做汉化，保留了广告，也是考虑到我没权利做这种损害他人原本权益的事情。

同时可能有部分zz发言，以及携带中文界面截屏的问题反馈让开发者感到不愉快。稍微换位思考一下就可以理解🤦️。  回到做法本身来看，确实语言门槛可以很方便地筛除部分低龄低文化水平的zz用户，但是也把部分喜爱中文界面和遵守社区规章，懂礼貌的小白用户拒之门外了，有利有弊。  不过F大如何处置自己的劳动成果，任何人都无权干涉也没有资格去做评价。先从努力学习英文和习惯英文界面开始吧🌚。️

**Comment by ZerOri** [comment]
> > 实在搞不懂CFW开发者意图，不想加入中文仅仅是为了提高小白使用门槛？
> 
> 之前有部分人提供的中文包是剔除了介绍界面的广告的，这点显然触碰到了开发者的利益。我的这个汉化包只对界面做汉化，保留了广告，也是考虑到我没权利做这种侵犯他人原本权益的事情。
> 
> 同时可能有部分zz发言，以及携带中文界面截屏的问题反馈让开发者感到不愉快。稍微换位思考一下就可以理解🤦️。  回到做法本身来看，确实语言门槛可以很方便地筛除部分低龄低文化水平的zz用户，但是也把部分喜爱中文界面和遵守社区规章，懂礼貌的小白用户拒之门外了，有利有弊。  不过F大如何处置自己的劳动成果，任何人都无权干涉也没有资格去做评价。先从努力学习英文和习惯英文界面开始吧🌚。️

感谢说明，不过我个人只是因为强迫症而更喜欢中文界面UI，英文也能看的懂，就是有点膈应，诚然，作为用户确实没有权利对开发者的决定指手画脚，看看以后有没有更好的替代方案吧。

**Comment by sunbin7288** [comment]
> > > 实在搞不懂CFW开发者意图，不想加入中文仅仅是为了提高小白使用门槛？
> 
> > 
> 
> > 之前有部分人提供的中文包是剔除了介绍界面的广告的，这点显然触碰到了开发者的利益。我的这个汉化包只对界面做汉化，保留了广告，也是考虑到我没权利做这种侵犯他人原本权益的事情。
> 
> > 
> 
> > 同时可能有部分zz发言，以及携带中文界面截屏的问题反馈让开发者感到不愉快。稍微换位思考一下就可以理解🤦️。
> 
> 回到做法本身来看，确实语言门槛可以很方便地筛除部分低龄低文化水平的zz用户，但是也把部分喜爱中文界面和遵守社区规章，懂礼貌的小白用户拒之门外了，有利有弊。
> 
> 不过F大如何处置自己的劳动成果，任何人都无权干涉也没有资格去做评价。先从努力学习英文和习惯英文界面开始吧🌚。️
> 
> 
> 
> 感谢说明，不过我个人只是因为强迫症而更喜欢中文界面UI，英文也能看的懂，就是有点膈应，诚然，作为用户确实没有权利对开发者的决定指手画脚，看看以后有没有更好的替代方案吧。

我也是，就是纯粹的不习惯 强迫症！如果是个国外的开发者就算了，明明是中国人开发的，非要这样搞！

**Comment by ZerOri** [comment]
> > > > 实在搞不懂CFW开发者意图，不想加入中文仅仅是为了提高小白使用门槛？
> > 
> > 
> > > 
> > 
> > 
> > > 之前有部分人提供的中文包是剔除了介绍界面的广告的，这点显然触碰到了开发者的利益。我的这个汉化包只对界面做汉化，保留了广告，也是考虑到我没权利做这种侵犯他人原本权益的事情。
> > 
> > 
> > > 
> > 
> > 
> > > 同时可能有部分zz发言，以及携带中文界面截屏的问题反馈让开发者感到不愉快。稍微换位思考一下就可以理解🤦️。
> > 
> > 
> > 回到做法本身来看，确实语言门槛可以很方便地筛除部分低龄低文化水平的zz用户，但是也把部分喜爱中文界面和遵守社区规章，懂礼貌的小白用户拒之门外了，有利有弊。
> > 不过F大如何处置自己的劳动成果，任何人都无权干涉也没有资格去做评价。先从努力学习英文和习惯英文界面开始吧🌚。️
> > 感谢说明，不过我个人只是因为强迫症而更喜欢中文界面UI，英文也能看的懂，就是有点膈应，诚然，作为用户确实没有权利对开发者的决定指手画脚，看看以后有没有更好的替代方案吧。
> 
> 我也是，就是纯粹的不习惯 强迫症！如果是个国外的开发者就算了，明明是中国人开发的，非要这样搞！

这也是没得办法的事，作者可能就是不想给小白用户用，毕竟翻墙用户鱼龙混杂，确实有很多不守规矩的小白用户

**Comment by ZerOri** [comment]
> > > > 实在搞不懂CFW开发者意图，不想加入中文仅仅是为了提高小白使用门槛？
> > 
> > 
> > > 
> > 
> > 
> > > 之前有部分人提供的中文包是剔除了介绍界面的广告的，这点显然触碰到了开发者的利益。我的这个汉化包只对界面做汉化，保留了广告，也是考虑到我没权利做这种侵犯他人原本权益的事情。
> > 
> > 
> > > 
> > 
> > 
> > > 同时可能有部分zz发言，以及携带中文界面截屏的问题反馈让开发者感到不愉快。稍微换位思考一下就可以理解🤦️。
> > 
> > 
> > 回到做法本身来看，确实语言门槛可以很方便地筛除部分低龄低文化水平的zz用户，但是也把部分喜爱中文界面和遵守社区规章，懂礼貌的小白用户拒之门外了，有利有弊。
> > 不过F大如何处置自己的劳动成果，任何人都无权干涉也没有资格去做评价。先从努力学习英文和习惯英文界面开始吧🌚。️
> > 感谢说明，不过我个人只是因为强迫症而更喜欢中文界面UI，英文也能看的懂，就是有点膈应，诚然，作为用户确实没有权利对开发者的决定指手画脚，看看以后有没有更好的替代方案吧。
> 
> 我也是，就是纯粹的不习惯 强迫症！如果是个国外的开发者就算了，明明是中国人开发的，非要这样搞！

@ClashR_for_Windows_Channel 可以进这个tg频道，里面有持续更新

**Comment by bigbaldy1128** [comment]
我一直不明白一件事，就是为何CFW不开源，十分令人不解

**Comment by ZerOri** [comment]
> 我一直不明白一件事，就是为何CFW不开源，十分令人不解

人家大佬说不开源就不开源😀不为什么
